name: Build, test, release

on:
  push:

jobs:
  minizinc:
    name: Build wasm version of MiniZinc
    runs-on: ubuntu-latest
    container: emscripten/emsdk
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "minizinc/libminizinc"
          ref: "develop"
      - name: Download vendor
        run: ./download_vendor
        env:
          MZNARCH: wasm
      - name: Get MiniZinc Revision
        id: get-minizinc-rev
        run: echo "rev=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Cache MiniZinc Build
        id: cache
        uses: actions/cache@v3
        with:
          path: minizinc
          key: minizinc-${{ steps.get-minizinc-rev.outputs.rev }}-${{ hashFiles('vendor/version.json') }}
      - name: Configure MiniZinc
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          emcmake cmake -S . -B build \
            -DCMAKE_FIND_ROOT_PATH="/" \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_REF=$GITHUB_RUN_NUMBER \
            -DGecode_ROOT="$GITHUB_WORKSPACE/vendor/gecode" \
            -DOsiCBC_ROOT="$GITHUB_WORKSPACE/vendor/cbc" \
            -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/minizinc"
      - name: Build MiniZinc
        if: steps.cache.outputs.cache-hit != 'true'
        run: cmake --build build --config Release --target install -j 2
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: minizinc
          path: minizinc/

  build:
    name: Build, test and release minizinc-js
    runs-on: ubuntu-latest
    needs: [minizinc]
    env:
      MZN_WASM_DIR: ${{ github.workspace }}/minizinc
      MZN_NODE_BINARY: ${{ github.workspace }}/native/bin/minizinc
    steps:
      - uses: actions/checkout@v3
      - name: Fetch MiniZinc
        uses: actions/download-artifact@v3
        with:
          name: minizinc
          path: ${{ github.workspace }}/minizinc
      - name: Fetch MiniZinc image
        uses: docker://minizinc/minizinc:edge
        with:
          args: sh -c 'mkdir -p $GITHUB_WORKSPACE/native && cp -r /usr/local/* $GITHUB_WORKSPACE/native'
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Build docs
        run: npm run docs
      - name: Create package
        run: npm pack
      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: minizinc-*.tgz
